version: '3'
services:
  kickup-soccer:
    image: scottzyang/kickup-soccer:latest
    environment:
      DATABASE_URL: postgres://kickup:soccer@postgres:5432/kickupappdb
      SECRET_KEY: itsasecret
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: kickup
      POSTGRES_PASSWORD: soccer
      POSTGRES_DB: kickupappdb
    restart: always
